# Generated by Django 6.0.3 on 2026-04-03 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('member', 'Membro'), ('coorganizer', 'Coorganizador'), ('moderator', 'Moderador')], default='member', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativo'), ('rejected', 'Rejeitado'), ('removed', 'Removido')], default='active', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Público'), ('private', 'Privado')], default='public', max_length=32)),
                ('access_rule', models.CharField(choices=[('open', 'Livre'), ('approval', 'Aprovação')], default='open', max_length=32)),
                ('required_plan', models.CharField(choices=[('none', 'Sem restrição'), ('free', 'Gratuito'), ('silver', 'Silver'), ('gold', 'Gold')], default='none', max_length=32)),
                ('rules', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.city')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
