# Generated by Django 6.0.3 on 2026-04-03 22:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('push', 'Push')], max_length=32)),
                ('kind', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
