# Generated by Django 6.0.3 on 2026-04-03 22:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('proprietary', 'Proprietário')], max_length=32)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('created', 'Criada'), ('pending', 'Pendente'), ('paid', 'Paga'), ('failed', 'Falhou'), ('refunded', 'Reembolsada')], default='created', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=8)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
